/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model2.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model2(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("models/model2.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="model_LOD0"
            geometry={nodes.model_LOD0.geometry}
            material={nodes.model_LOD0.material}
            skeleton={nodes.model_LOD0.skeleton}
          />
          <skinnedMesh
            name="model_LOD1"
            geometry={nodes.model_LOD1.geometry}
            material={nodes.model_LOD1.material}
            skeleton={nodes.model_LOD1.skeleton}
          />
          <skinnedMesh
            name="model_LOD2"
            geometry={nodes.model_LOD2.geometry}
            material={nodes.model_LOD2.material}
            skeleton={nodes.model_LOD2.skeleton}
          />
          <skinnedMesh
            name="model_LOD3"
            geometry={nodes.model_LOD3.geometry}
            material={nodes.model_LOD3.material}
            skeleton={nodes.model_LOD3.skeleton}
          />
          <skinnedMesh
            name="model_LOD4"
            geometry={nodes.model_LOD4.geometry}
            material={nodes.model_LOD4.material}
            skeleton={nodes.model_LOD4.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/model2.glb");
