const services = [
  {
    name: "Media Production",
    link: "",
    image: "/images/services/media.webp",
    type: "ac",
    images: [
      "/images/mediaprod/image-1.webp",
      "/images/mediaprod/image-2.webp",
      "/images/mediaprod/image-3.webp",
    ],
  },
  {
    name: "Social Media Marketing",
    link: "",
    image: "/images/services/SOCIAL MEDIA COVER.webp",
    type: "ac",
    images: [
      "/images/socialMediaMarketing/image-1.webp",
      "/images/socialMediaMarketing/image-2.webp",
      "/images/socialMediaMarketing/image-3.webp",
    ],
  },
  {
    name: "Branding",
    link: "",
    image: "/images/services/branding.webp",
    type: "ac",
    images: [
      "/images/branding/image-1.webp",
      "/images/branding/image-2.webp",
      "/images/branding/image-3.webp",
      "/images/branding/image-4.webp",
    ],
  },
  {
    name: "Printing Services",
    link: "",
    image: "/images/services/printing.webp",
    type: "ac",
    images: ["/images/printing/image-1.webp", "/images/printing/image-2.webp"],
  },
  {
    name: "Web Development",
    link: "",
    image: "/images/services/WEBSITE DEV COVER.webp",
    type: "ac",
    images: [
      "/images/websites/image-1.webp",
      "/images/websites/image-2.webp",
      "/images/websites/image-3.webp",
      "/images/websites/image-4.webp",
      "/images/websites/image-5.webp",
      "/images/websites/image-6.webp",
    ],
  },
  {
    name: "App Development",
    link: "",
    image: "/images/services/app.webp",
    type: "ac",
    images: ["/images/appDev/appDev.webp"],
  },
  {
    name: "Content Marketing",
    link: "",
    image: "/images/services/content marketing.webp",
    type: "text",
    text: "We specialize in content marketing that goes beyond just writing blogs or posting on social media — we create strategic, high-impact content that builds trust, drives organic traffic, and converts your audience into loyal customers. By combining compelling storytelling with SEO best practices and data-driven strategies, we help your brand stand out, rank higher, and grow faster across every digital channel.",
    images: ["/images/contentMarketing/content-marketing.webp"],
  },
  {
    name: "Creative Services",
    link: "",
    image: "/images/services/CREATIVE SERVICES.webp",
    type: "ac",
    images: [
      "/images/creativeServices/image-1.webp",
      "/images/creativeServices/image-2.webp",
      "/images/creativeServices/image-3.webp",
      "/images/creativeServices/image-4.webp",
    ],
  },
  {
    name: "Indoor & Outdoor LED Signage",
    link: "",
    image: "/images/services/led signage.webp",
    type: "vc",
    images: [
      "/images/signage/signage_1.webp",
      "/images/signage/signage_2.webp",
      "/images/signage/signage_3.webp",
      "/images/signage/signage_4.webp",
      "/images/signage/signage_5.webp",
      "/images/signage/signage_6.webp",
      "/images/signage/signage_7.webp",
      "/images/signage/signage_8.webp",
      "/images/signage/signage_9.webp",
      "/images/signage/signage_10.webp",
      "/images/signage/signage_11.webp",
      "/images/signage/signage_12.webp",
      "/images/signage/signage_13.webp",
      "/images/signage/signage_14.webp",
      "/images/signage/signage_15.webp",
      "/images/signage/signage_16.webp",
      "/images/signage/signage_17.webp",
      "/images/signage/signage_18.webp",
      "/images/signage/signage_19.webp",
      "/images/signage/signage_20.webp",
    ],
  },
];

export { services };
