const services = [
  {
    name: "Media Production",
    link: "",
    image: "/images/services/media_adjusted.webp",
    type: "ac",
    images: [
      "/images/signage/signage_1.webp",
      "/images/signage/signage_2.webp",
      "/images/signage/signage_3.webp",
      "/images/signage/signage_4.webp",
      "/images/signage/signage_5.webp",
      "/images/signage/signage_6.webp",
      "/images/signage/signage_7.webp",
      "/images/signage/signage_8.webp",
      "/images/signage/signage_9.webp",
      "/images/signage/signage_10.webp",
      "/images/signage/signage_11.webp",
      "/images/signage/signage_12.webp",
      "/images/signage/signage_13.webp",
      "/images/signage/signage_14.webp",
      "/images/signage/signage_15.webp",
      "/images/signage/signage_16.webp",
      "/images/signage/signage_17.webp",
      "/images/signage/signage_18.webp",
      "/images/signage/signage_19.webp",
      "/images/signage/signage_20.webp",
    ],
  },
  {
    name: "Social Media Marketing",
    link: "",
    image: "/images/services/digital.webp",
  },
  {
    name: "Branding",
    link: "",
    image: "/images/services/branding_adjusted.webp",
    type: "ac",
    images: [
      "/images/branding/image-1.webp",
      "/images/branding/image-2.webp",
      "/images/branding/image-3.webp",
      "/images/branding/image-4.webp",
    ],
  },
  {
    name: "Printing Services",
    link: "",
    image: "/images/services/printing_adjusted.webp",
  },
  {
    name: "Web Development",
    link: "",
    image: "/images/services/webDev_adjusted.webp",
    type: "ac",
    images: [
      "/images/websites/image-1.webp",
      "/images/websites/image-2.webp",
      "/images/websites/image-3.webp",
      "/images/websites/image-4.webp",
      "/images/websites/image-5.webp",
      "/images/websites/image-6.webp",
    ],
  },
  {
    name: "App Development",
    link: "",
    image: "/images/services/appDev_adjusted.webp",
  },
  {
    name: "Strategic Marketing",
    link: "",
    image: "/images/services/marketing_adjusted.webp",
  },
  {
    name: "Grpahic Designing",
    link: "",
    image: "/images/services/graphic_adjusted.webp",
  },
  {
    name: "Indoor & Outdoor LED Signage",
    link: "",
    image: "/images/services/advertising_adjusted.webp",
    type: "vc",
    images: [
      "/images/signage/signage_1.webp",
      "/images/signage/signage_2.webp",
      "/images/signage/signage_3.webp",
      "/images/signage/signage_4.webp",
      "/images/signage/signage_5.webp",
      "/images/signage/signage_6.webp",
      "/images/signage/signage_7.webp",
      "/images/signage/signage_8.webp",
      "/images/signage/signage_9.webp",
      "/images/signage/signage_10.webp",
      "/images/signage/signage_11.webp",
      "/images/signage/signage_12.webp",
      "/images/signage/signage_13.webp",
      "/images/signage/signage_14.webp",
      "/images/signage/signage_15.webp",
      "/images/signage/signage_16.webp",
      "/images/signage/signage_17.webp",
      "/images/signage/signage_18.webp",
      "/images/signage/signage_19.webp",
      "/images/signage/signage_20.webp",
    ],
  },
];

export { services };
